targets = []
all-features = false
no-default-features = false
feature-depth = 1

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
# RUSTSEC-2022-0044 states that markdown is unmaintained, but in the real world only v0.3.0 and older are unmaintained.
# Control over the markdown crate switched to wooorm @ https://github.com/wooorm/markdown-rs/ with v1.0.0-alpha.1.
ignore = ["RUSTSEC-2022-0044"]

[licenses]
unlicensed = "deny"
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "MPL-2.0",
  "ISC",
  "Unicode-DFS-2016",
  "Zlib",
  "LGPL-3.0",
  "AGPL-3.0",
  "OpenSSL",
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = []

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
