env = "Development"

[server]
url = "127.0.0.1"
fqdn = "http://127.0.0.1:3000"
cdn_fqdn = "http://127.0.0.1:3000"
api_fqdn = "http://127.0.0.1:8000/api"
api_root_fqdn = "http://127.0.0.1:8000"
jwt_secret = "super-secret-key"

[database]
url = "postgresql://chameleon:chameleon@127.0.0.1:5432/chameleon"
max_connections = 5

[cdn]
file_store = "Local"

[queue]
queue_backend = "RabbitMQ"
work_queue = "work_q"
work_deadletter_queue = "work_dq"

[log]
level = "Debug"

[app]
imagemagick_exe_path = "convert"
secure = false
verify_external_https_certificates = false
