env = "Development"

[server]
url = "localhost"
fqdn = "http://localhost:3000"
cdn_fqdn = "http://localhost:3000"
api_fqdn = "http://localhost:8000/api"
api_root_fqdn = "http://localhost:8000"
jwt_secret = "super-secret-key"

[database]
url = "postgresql://orbit:orbit@localhost:5432/orbit"
host = "localhost"
port = 5432
database = "orbit"
username = "orbit"
password = "orbit"
max_connections = 5

[cdn]
file_store = "Local"

[queue]
queue_backend = "RabbitMQ"
work_queue = "work_q"
work_deadletter_queue = "work_dq"
schedule_jobs = true

[log]
level = "Debug"

[app]
imagemagick_exe_path = "convert"
secure = false
verify_external_https_certificates = false
